version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: foodgram-db
    env_file:
      - ./.env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  backend:
    image: vasiluk23/foodgram_backend:latest
    container_name: foodgram-backend
    env_file:
      - ./.env
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: vasiluk23/foodgram_frontend:latest
    container_name: foodgram-frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: vasiluk23/foodgram_nginx:latest
    container_name: foodgram-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email vasiluk23@yandex.ru --agree-tos --no-eff-email -d vaska.tech -d www.vaska.tech

volumes:
  postgres_data:
  static_volume:
  media_volume:
