version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: foodgram-db
    env_file:
      - ./.env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  backend:
    image: vasiluk23/foodgram_backend:latest
    container_name: foodgram-backend
    env_file:
      - ./.env
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: vasiluk23/foodgram_frontend:latest
    container_name: foodgram-frontend
    restart: always
    command: sh -c "npm run build && cp -r build/* /usr/share/nginx/html/"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  nginx:
    image: vasiluk23/foodgram_nginx:latest
    container_name: foodgram-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static/
      - media_volume:/app/media/
      - ./frontend/build:/usr/share/nginx/html
      - ./docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume:
