version: '3.8'

services:
  db:
    restart: always
    env_file:
      - ./.env
    image: postgres:13-alpine
    container_name: foodgram-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'


  backend:
#    image: vasiluk23/foodgram-backend:latest
    restart: always
    env_file:
      - ./.env
    build:
      context: ./backend
    container_name: foodgram-backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db


  frontend:
#    image: vasiluk23/foodgram-frontend:latest
    build:
      context: ./frontend
    container_name: foodgram-frontend
    command: sh -c "npm run build && cp -r build/* /usr/share/nginx/html/"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend


  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - ./frontend/build:/usr/share/nginx/html
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume:
