# Максимальные длины строковых полей
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 15
MAX_LENGTH_TAG_NAME = 50
MAX_LENGTH_COLOR_CODE = 7
MAX_LENGTH_SLUG = 50
MAX_LENGTH_RECIPE_NAME = 200

# Регулярные выражения
HEX_COLOR_CODE_REGEX = r'^#([A-Fa-f0-9]{6})$'

# Значения для валидации
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32_000
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32_000

# Значения для тестов
RECIPE_COOKING_TIME = 10
RECIPE_INGREDIENT_AMOUNT = 100
